### ISSUE TITLE
Can't craft primitive butchering table with non stone axes

### ISSUE THREAD

**Issue by ShubiMaja** [Alathra/AlathraExtrasVS#20]
Can't craft primitive butchering table with non stone axes

![Image](https://github.com/user-attachments/assets/2ac2cf3c-358b-4a79-a79d-a1c896c6fd00)

**Comment by BinglPringl** [comment]
I think this is intentional and designed to be a more primitive look to that primitive table. Plus, it says tools are consumed upon craft, so having it be craftable with other axes would only make people upset that they lost their metal axe.

**Comment by ShubiMaja** [comment]
Agreed. Won't do.
