### ISSUE TITLE
Bear head helmet requires brown bear fur

### ISSUE THREAD

**Issue by ShubiMaja** [Alathra/AlathraExtrasVS#21]
Inconsistent with other recipes 

![Image](https://github.com/user-attachments/assets/f8dc6e47-d648-46ee-904e-18ac8adb5ea7)

**Comment by BinglPringl** [comment]
Fixed. Will be up in next pr

**Comment by ShubiMaja** [comment]
@BinglPringl please link or associate pr so we can track fixes.
