### ISSUE TITLE
Tailored wool gamboised - repair bugs

### ISSUE THREAD

**Issue by ShubiMaja** [Alathra/AlathraExtrasVS#28]
Tailored wool gamboised helmet repair bug

Olivia Schuler (⚓ Tremontaine)
OP
 — 11/27/2024 8:26 AM
The recipe to repair a wool gamboised helmet is broken. As can be seen in the screenshot, it requires gamboised leg armor to make a repaired helmet. I imagine repairing wool gamboised leg armor would also be affected by this.
Image
https://discord.com/channels/1289397978737676329/1311216662510571521/1311216662510571521

**Comment by ShubiMaja** [comment]
Olivia Schuler (⚓ Tremontaine)
OP
 — 11/28/2024 2:08 AM
Some other repair recipes don't seem to be working either. I attempted to repair some plain tailored linen gambeson with plain cloth and it didn't work

**Comment by ShubiMaja** [comment]
@BinglPringl please link to the pr that fixed this and mark as complete

**Comment by BinglPringl** [comment]
https://github.com/Alathra/AlathraExtrasVS/pull/26
