### ISSUE TITLE
xskill exp missing from Wildcraft

### ISSUE THREAD

**Issue by ShubiMaja** [Alathra/AlathraExtrasVS#29]
https://discord.com/channels/1289397978737676329/1305925345861570612/1305925345861570612
Jenpai (Lithium)
OP
 — 11/12/2024 6:01 PM
Noticed none of the wildcraft stuff is giving exp, such as the various fruit and berries and herbs.

**Comment by ShubiMaja** [comment]
@BinglPringl Please link PR and mark complete

**Comment by BinglPringl** [comment]
ignore the massive list of pr links. i kinda missed what i wanted but we're good now
