### ISSUE TITLE
copper anvil deconstruction / chisel recipe conflicts with decorative anvil recipe

### ISSUE THREAD

**Issue by ShubiMaja** [Alathra/AlathraExtrasVS#5]
Just need to pick a different recipe for one of them.

![Image](https://github.com/user-attachments/assets/d0991cfd-75a8-40dc-923c-de5ef948347f)
![Image](https://github.com/user-attachments/assets/87e8c652-c4c2-46b3-8ee0-7e450e205191)
![Image](https://github.com/user-attachments/assets/1752a6e8-3dff-4570-801a-015bfacf2db7)

**Comment by Oktolina** [comment]
Question: is that not a different type of chisel?

**Comment by BinglPringl** [comment]
Not a bug. Breaking down anvil is a shapeless recipe, so the decorative anvil recipe doesn't override it.

![Image](https://github.com/user-attachments/assets/de2e700f-9f3d-4260-945d-49e0b958e667)
