### ISSUE TITLE
add way to get jute and cotton after adding hide and fabric

### ISSUE THREAD

**Issue by ShubiMaja** [Alathra/AlathraExtrasVS#7]
https://discord.com/channels/1289397978737676329/1304889537335529563

Some ideas being considered at the moment are

- adding it to the trader tables
- adding a few random caches of it
- Making it part of Farming loot for Treasure vessels

**Comment by BinglPringl** [comment]
Currently fixing this issue. Planning on adding it to the trader table for now. If more changes are necessary, I will update here.

Update: Cotton seeds are already being sold by the clothing trader, not agricultural. As for jute, it will be added to the agricultural trader's table.
